apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  # exposes the service on a cluster-internal IP. Choosing this values makes the service only reachable from within the cluster. This is the default ServiceType.
  type: ClusterIP
  selector:
    component: web
  ports:
    # port on the service
    - port: 3000
      # port inside the container
      targetPort: 3000
