apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      # allocate pvc for this particular pod
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          # config to specify the volume to use in this container
          volumeMounts:
            - name: postgres-storage
              # path to mount the volumne inside the container, all the container stores at the folder or inside that directory will be actually stored inside of our volume
              mountPath: /var/lib/postgresql/data
              # config only for postgres instance
              subPath: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PG_PASSWORD
